// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";



export const metadata: Metadata = {
  title: "LEVVE - Emagreça com comida acessível e acompanhamento por IA",
  description: "Planos alimentares simples, marmitas fit com preço estimado e acompanhamento diário por inteligência artificial. Feito para o brasileiro real.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
