// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import AppHeader from "@/components/AppHeader";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ ÍCONE OFICIAL ÚNICO DO LEVVE
const LEVVE_ICON_URL = "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/d9105710-f327-4523-baac-b94260b09d28.jpg";

export const metadata: Metadata = {
  title: "Levve - Emagreça com comida acessível e acompanhamento por IA",
  description: "Planos alimentares simples, marmitas fit com preço estimado e acompanhamento diário por inteligência artificial. Feito para o brasileiro real.",
  icons: {
    icon: [
      { url: LEVVE_ICON_URL, sizes: "32x32", type: "image/jpeg" },
      { url: LEVVE_ICON_URL, sizes: "16x16", type: "image/jpeg" },
      { url: LEVVE_ICON_URL, sizes: "192x192", type: "image/jpeg" },
      { url: LEVVE_ICON_URL, sizes: "512x512", type: "image/jpeg" }
    ],
    apple: [
      { url: LEVVE_ICON_URL, sizes: "180x180", type: "image/jpeg" },
      { url: LEVVE_ICON_URL, sizes: "152x152", type: "image/jpeg" },
      { url: LEVVE_ICON_URL, sizes: "120x120", type: "image/jpeg" }
    ],
    other: [
      { url: LEVVE_ICON_URL, sizes: "1024x1024", type: "image/jpeg" },
      { url: LEVVE_ICON_URL, sizes: "64x64", type: "image/jpeg" }
    ]
  },
  manifest: "/manifest.json",
  openGraph: {
    title: "Levve - Emagreça com comida acessível e acompanhamento por IA",
    description: "Planos alimentares simples, marmitas fit com preço estimado e acompanhamento diário por inteligência artificial.",
    images: [{ url: LEVVE_ICON_URL }],
  },
  twitter: {
    card: "summary",
    title: "Levve - Emagreça com comida acessível e acompanhamento por IA",
    description: "Planos alimentares simples, marmitas fit com preço estimado e acompanhamento diário por inteligência artificial.",
    images: [LEVVE_ICON_URL],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href={LEVVE_ICON_URL} type="image/jpeg" sizes="32x32" />
        <link rel="icon" href={LEVVE_ICON_URL} type="image/jpeg" sizes="16x16" />
        <link rel="apple-touch-icon" href={LEVVE_ICON_URL} sizes="180x180" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2E5BFF" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AppHeader />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
